### ISSUE TITLE
Error in eigen(private$.susceptibility * self$contact) : 0 x 0 matrix

### ISSUE THREAD

**Issue by Rantala-hus** [PascalCrepey/HospiCoV#1]
Hi

and thank you for creating this model! 

I'm running in the error message in the title when trying to run the shiny_app(). Do I need to initialize some other values in addition to the contact matrices?

The whole error message is 
>\> shiny_app()
>
>Listening on http://127.0.0.1:4552
>Warning: Error in eigen: 0 x 0 matrix
>  62: stop
>  61: eigen
>  60: .subset2(public_bind_env, "initialize")
>  59: Parameters$new
>  58: module
>  53: callModule
>  52: server
>Error in eigen(private$.susceptibility * self$contact) : 0 x 0 matrix

**Comment by ClementMassonnaud** [comment]
Hello,
Can you please tell us what operating system you are using?
In the meantime, you can access the app online here: http://hospicov.ehesp.fr/

**Comment by Rantala-hus** [comment]
Hi,

Ubuntu 18.04, but on a virtual machine. Could that affect something?

The hospicov:Parameters seem to contain these values but they are mostly NULL

>\> hospicov::Parameters
<Parameters> object generator
  Public:
    nage: 0
    preImmune: NULL
    preExposed: NULL
    preInfected: NULL
    symptomatic: NULL
    progression: NULL
    beta: NULL
    school: NULL
    home: NULL
    work: NULL
    other: NULL
    agegroupnames: NULL
    initialize: function (R0 = 2.2)
    getList: function ()
    clone: function (deep = FALSE)
  Active bindings:
    susceptibility: function (x)
    R0: function (value)
    removal: function (x)
    duration: function (x)
    nbDays: function (x)
  Private:
    .susceptibility: NULL
    .R0: NULL
    .duration: Trimester
    .nbDays: 90
    .removal: NULL
  Parent env: <environment: namespace:hospicov>
  Locked objects: TRUE
  Locked class: FALSE
  Portable: TRUE

**Comment by ClementMassonnaud** [comment]
The virtual machine is not an issue
There was an issue in the Parameters script indeed. It should be fixed now
Please try to install the latest dev version (not released yet) with the following command

```R
devtools::install_github("PascalCrepey/HospiCoV")
```
And tell us if it is ok now

**Comment by Rantala-hus** [comment]
Works nicely now, thanks!
